# Generated by Django 5.1.2 on 2024-10-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTP1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
